---
driver:
  name: vagrant
  customize:
    memory: 3072
  network:
    # Allow access to the aem webui which is useful when troubleshooting
      - - forwarded_port
        - guest: 4502
          host: 4502
          auto_correct: true
provisioner:
  name: chef_zero
  environments_path: './test/environments'
  roles_path: './test/roles'
  data_bags_path: './test/integration/data_bags'

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[aem::_base_aem_setup]
      - recipe[aem::author]
      - role[aem]
    attributes:
    provisioner:
